### ISSUE TITLE
Book of similar kanji

### ISSUE THREAD

**Issue by setsumi** [siikamiika/similar-kanji#1]
Hello.
Stumbled upon a book of similar kanji so here is the list of them. Not sure now to apply this to the project. Posting just in case it may be useful somehow.

![p0001](https://cloud.githubusercontent.com/assets/5970554/22331886/3b68dbe8-e411-11e6-80aa-25c57f1dc752.png)
![p0002](https://cloud.githubusercontent.com/assets/5970554/22331926/6d48436a-e411-11e6-947e-68cde9baa8cf.png)
![p0003](https://cloud.githubusercontent.com/assets/5970554/22331929/6efbb8fe-e411-11e6-9758-25e075e236e7.png)
![p0004](https://cloud.githubusercontent.com/assets/5970554/22331933/710d4c7a-e411-11e6-9839-d8137d5e65d9.png)

**Comment by siikamiika** [comment]
Thanks!

What OCR do you normally use? I tried with my script that uses the Tesseract engine but the output is messy because the script is optimized for continuous text and not tabular data.

On the topic of more sources for similar kanji, I should use the project behind https://similarity.gakusha.info/ at some point to find some more unobvious similar kanji.

**Comment by setsumi** [comment]
Tried  読取革命 and Fine Reader and they made a mess. I better do it by hand and post results later.

That project looks good... at least for the machine generated output :)

**Comment by siikamiika** [comment]
Before you start going through them all, consider that pretty many of them are probably already in the file. Also they are divided in a 10x20 grid and not rotated much so knowing the coordinates of the grid's corners makes it possible to get the number left of the start of each group and kanji for more precise OCR. I'll look at it later.

**Comment by siikamiika** [comment]
Alright, [here](https://siikamiika.github.io/similar-kanji/ocr/) are the results. Some of them were incorrect but editing the correct characters to each text input lets you copy them as JSON that can be easily merged to the similar kanji file. You can do it if you want to. :D

I'm not sure if the recognition could have been improved by processing the images somehow, but it's definitely not worth it for this particular case. Maybe if I had a novel or something.

**Comment by setsumi** [comment]
Impressive! So easy now.
Here is the result.

[book-similars.txt](https://github.com/siikamiika/similar-kanji/files/735430/book-similars.txt)

The only issue is there are two groups №64 split by page break.

**Comment by siikamiika** [comment]
They had the same index so it wasn't a problem. Merged, thanks!
